#!/usr/bin/env python3

import rclpy
from rclpy.node import Node
from pepper_interfaces.srv import Text2Speech 
from pepper_nodes import PepperNode
from pepper_nodes.utils import Session

class Text2SpeechNode(PepperNode):

    def __init__(self):
        """
        The function initializes a Text2SpeechNode with necessary services and proxies.
        """
        super().__init__('text2speech_node')
        self.session = Session(self.ip, self.port)
        self.tts_proxy = self.session.get_service("ALTextToSpeech")
        self.audio_device_proxy = self.session.get_service("ALAudioDevice")
        self.tts_service = self.create_service(Text2Speech, 'tts', self.say_callback)
        self.get_logger().info("Text2SpeechNode initialized")

    def set_volume(self, volume: int):
        """
        The function `set_volume` sets the volume level for a text-to-speech request within a specified
        range.
        
        :param volume: The `volume` parameter in the `set_volume` method is an integer value
        representing the desired volume level. The method checks if the provided volume is within the
        valid range of 0 to 100 (inclusive) before setting the volume using the `audio_device_proxy` and
        logging the action
        :type volume: int
        :return: If the volume is equal to `Text2Speech.Request.NO_SET` or if the volume is not in the
        range of 0 to 100, then the function will return without setting the volume.
        """
        if volume == Text2Speech.Request.NO_SET:
            return
        if volume not in range(0, 101):
            self.get_logger().error("Volume not set for value {}. Must be between [0-100].".format(volume))
            return
        volume = int(volume)
        self.audio_device_proxy.setOutputVolume(volume)
        self.get_logger().info(f"Setting volume to {volume}")
    
    def set_language(self, language: str):
        """
        The function `set_language` sets the language for text-to-speech processing, with error handling
        for invalid language values.
        
        :param language: The `set_language` method takes a `language` parameter, which should be a
        string representing the language to set for text-to-speech functionality. The accepted values
        for the `language` parameter are English and Italian, represented by the constants.
        :type language: str
        :return: If the `language` parameter is an empty string, nothing is returned explicitly, but the
        function will exit early without setting the language or logging any messages. If the `language`
        parameter is not empty but is not one of the supported languages (English or Italian), an error
        message is logged, and the function will return without setting the language.
        """
        if language == "":
            return
        if language not in [Text2Speech.Request.ENGLISH, Text2Speech.Request.ITALIAN]:
            self.get_logger().error(f"Language not set for value {language}. Must be one among {[Text2Speech.Request.ENGLISH, Text2Speech.Request.ITALIAN]}")
            return
        self.tts_proxy.setLanguage(language)
        self.get_logger().info(f"Language set to {language}")
    
    def say_callback(self, request: Text2Speech.Request, response: Text2Speech.Response):
        """
        The function `say_callback` processes a text-to-speech request, handles exceptions, retries if
        necessary, and sends an acknowledgment response.
        
        :param request: The `request` parameter in the `say_callback` function is of type
        `Text2Speech.Request`. It contains information needed for the text-to-speech operation, such as
        the speech text, volume, and language settings
        :type request: Text2Speech.Request
        :param response: The `response` parameter in the `say_callback` function is an object of the
        `Text2Speech.Response` class. It is used to store the response generated by the function and set
        the acknowledgment message to "ACK" before returning it
        :type response: Text2Speech.Response
        :return: the `response` object after setting its `ack` attribute to "ACK".
        """
        try:
            speech = request.speech
            self.set_volume(request.volume)
            self.set_language(request.language)
            self.tts_proxy.say(speech)
        except Exception as e:
            self.get_logger().warn(f"TTS failed, retrying: {e}")
            self.session.reconnect()
            self.tts_proxy = self.session.get_service("ALTextToSpeech")
            self.audio_device_proxy = self.session.get_service("ALAudioDevice")
            speech = request.speech
            self.set_volume(request.volume)
            self.set_language(request.language)
            self.tts_proxy.say(speech)
        response.ack = "ACK"
        return response

def main():

    rclpy.init()
    node = Text2SpeechNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        import sys
        print(sys.exc_info())
        node.destroy_node()
        rclpy.shutdown()

if __name__ == '__main__':
    main()
