FROM ros:humble

RUN apt update && apt install -y iputils-ping net-tools nano gedit x11-apps mlocate python3-pip curl wget sudo

#Configure Timezone
RUN apt-get update && \
    apt-get install -yq tzdata && \
    ln -fs /usr/share/zoneinfo/Europe/Rome /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN pip install -U pip 
RUN apt update && apt install -y ros-humble-rviz2 \
                                ros-humble-rqt-common-plugins \
                                ros-humble-rqt-tf-tree \
                                ros-humble-rqt-image-view

WORKDIR /root/scripts                        
RUN pip install pyOpenssl -U

#User Creation
RUN useradd -m -s /bin/bash mivia \
    && echo 'mivia:mivia' | chpasswd \
    && usermod -aG sudo,dialout mivia 
RUN echo "mivia ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

#Installing RASA
WORKDIR /opt/
SHELL ["/bin/bash", "-c"]
RUN apt install -y python3.10-venv
RUN python3 -m venv venv --system-site-packages && \
    source venv/bin/activate && \
    pip install rasa==3.6.21 rasa[spacy] && \
    python -m spacy download en_core_web_md && \
    python -m spacy download it_core_news_md && \
    ln -s /opt/venv/bin/activate /usr/local/bin/activate_rasa_env && \
    chmod +x /usr/local/bin/activate_rasa_env

#Fix Pepper 230
WORKDIR /usr/local/bin
RUN apt update && apt install -y sshpass && \
    wget https://github.com/gdesimone97/cogrob_pepper_nodes/releases/download/fix-pepper/fix_pepper && \
    chmod +x fix_pepper

WORKDIR /root

#Installing GUI
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install xfce4 xfce4-goodies -y
RUN apt update && apt install xrdp -y
RUN update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper
RUN adduser xrdp ssl-cert 

#Installing LibGL
RUN apt install -y libx11-dev libgl1-mesa-glx libxext-dev

#Python utils
RUN pip install httpx

#Colcon utils
RUN echo "source /usr/share/colcon_cd/function/colcon_cd.sh" >> /home/mivia/.bashrc
RUN echo "export _colcon_cd_root=/opt/ros/humble/" >> /home/mivia/.bashrc
RUN echo "source /usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash" >> /home/mivia/.bashrc

#NAOqi
ADD --chown=mivia install_qi.bash /home/mivia/install_qi.bash
RUN chmod +x /home/mivia/install_qi.bash && bash /home/mivia/install_qi.bash

#Audio libs
RUN pip install sounddevice soundfile librosa
RUN apt update && apt install -y portaudio19-dev python3-pyaudio

#Transformers
RUN pip install --ignore-installed datasets \
                            torch==2.8.0 torchcodec \
                            transformers==4.56.1 bitsandbytes==0.47 accelerate \
                            huggingface_hub[cli]
RUN apt update && apt install -y ffmpeg git-lfs htop

#Transformers - Optimum
RUN pip install optimum onnx==1.19.0
ADD install_onnxruntime.bash /tmp
RUN bash /tmp/install_onnxruntime.bash

#Cleanup
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && rm -rf /root/.cache

#NO MOVE!
RUN pip install 'numpy<2' 'setuptools<80,>=30.3.0'

USER mivia
WORKDIR /home/mivia/
ADD --chown=mivia run_xrdp.bash .
RUN chmod +x run_xrdp.bash
RUN echo "xfce4-session" | tee .xsession

RUN echo "source /opt/ros/humble/setup.bash" >> .bashrc
ENV PATH=$PATH:/home/mivia/.local/bin

# RDP
EXPOSE 3389

# ROS
ENV ROS_LOCALHOST_ONLY=1
ENV ROS_DOMAIN_ID=0

#PYTHON
ENV PYTHONPATH=/workspace/demo_utils:$PYTHONPATH

ENTRYPOINT ["bash", "/home/mivia/run_xrdp.bash" ]