from ros_utils import ROS2Param

RESPEAKER_PARAMETERS_ROS = [
    ROS2Param(name="STATNOISEONOFF", value=True, description="Stationary noise suppression. 0 = OFF 1 = ON"),
    ROS2Param(name="GAMMA_ETAIL", value=3.000000, description="Over-subtraction factor of echo (tail components). min .. max attenuation"),
    ROS2Param(name="AGCTIME", value=0.982401, description="Ramps-up / down time-constant in seconds."),
    ROS2Param(name="GAMMA_NS_SR", value=1.000000, description="Over-subtraction factor of stationary noise for ASR.  [0.0 .. 3.0] (default: 1.0)"),
    ROS2Param(name="AGCDESIREDLEVEL", value=0.005000, description="Target power level of the output signal.  [-inf .. 0] dBov (default: -23dBov = 10log10(0.005))"),
    ROS2Param(name="MIN_NN_SR", value=0.300000, description="Gain-floor for non-stationary noise suppression for ASR. [-inf .. 0] dB (default: -10dB = 20log10(0.3))"),
    ROS2Param(name="STATNOISEONOFF_SR", value=True, description="Stationary noise suppression for ASR. 0 = OFF 1 = ON"),
    ROS2Param(name="MIN_NS_SR", value=0.150000, description="Gain-floor for stationary noise suppression for ASR. [-inf .. 0] dB (default: -16dB = 20log10(0.15))"),
    ROS2Param(name="GAMMA_ENL", value=1.000000, description="Over-subtraction factor of non-linear echo. min .. max attenuation"),
    ROS2Param(name="NLAEC_MODE", value=0, description="Non-Linear AEC training mode. 0 = OFF 1 = ON - phase 1 2 = ON - phase 2"),
    ROS2Param(name="TRANSIENTONOFF", value=True, description="Transient echo suppression. 0 = OFF 1 = ON"),
    ROS2Param(name="RT60ONOFF", value=True, description="RT60 Estimation for AES. 0 = OFF 1 = ON"),
    ROS2Param(name="AGCGAIN", value=11.119642, description="Current AGC gain factor.  [0 .. 60] dB (default: 0.0dB = 20log10(1.0))"),
    ROS2Param(name="NONSTATNOISEONOFF", value=True, description="Non-stationary noise suppression. 0 = OFF 1 = ON"),
    ROS2Param(name="AECFREEZEONOFF", value=False, description="Adaptive Echo Canceler updates inhibit. 0 = Adaptation enabled 1 = Freeze adaptation, filter only"),
    ROS2Param(name="AGCMAXGAIN", value=31.600000, description="Maximum AGC gain factor.  [0 .. 60] dB (default 30dB = 20log10(31.6))"),
    ROS2Param(name="CNIONOFF", value=True, description="Comfort Noise Insertion. 0 = OFF 1 = ON"),
    ROS2Param(name="NONSTATNOISEONOFF_SR", value=True, description="Non-stationary noise suppression for ASR. 0 = OFF 1 = ON"),
    ROS2Param(name="NLATTENONOFF", value=False, description="Non-Linear echo attenuation. 0 = OFF 1 = ON"),
    ROS2Param(name="ECHOONOFF", value=True, description="Echo suppression. 0 = OFF 1 = ON"),
    ROS2Param(name="AECNORM", value=2.000000, description="Limit on norm of AEC filter coefficients"),
    ROS2Param(name="AECSILENCELEVEL", value=0.000000, description="Threshold for signal detection in AEC [-inf .. 0] dBov (Default: -80dBov = 10log10(1x10-8))"),
    ROS2Param(name="GAMMA_E", value=1.000000, description="Over-subtraction factor of echo (direct and early components). min .. max attenuation"),
    ROS2Param(name="FREEZEONOFF", value=False, description="Adaptive beamformer updates. 0 = Adaptation enabled 1 = Freeze adaptation, filter only"),
    ROS2Param(name="AGCONOFF", value=True, description="Automatic Gain Control.  0 = OFF  1 = ON"),
    ROS2Param(name="MIN_NN", value=0.300000, description="Gain-floor for non-stationary noise suppression. [-inf .. 0] dB (default: -10dB = 20log10(0.3))"),
    ROS2Param(name="MIN_NS", value=0.150000, description="Gain-floor for stationary noise suppression. [-inf .. 0] dB (default: -16dB = 20log10(0.15))"),
    ROS2Param(name="GAMMA_NS", value=1.000000, description="Over-subtraction factor of stationary noise. min .. max attenuation"),
    ROS2Param(name="HPFONOFF", value=1, description="High-pass Filter on microphone signals. 0 = OFF 1 = ON - 70 Hz cut-off 2 = ON - 125 Hz cut-off 3 = ON - 180 Hz cut-off"),
    ROS2Param(name="GAMMAVAD_SR", value=15.000000, description="Set the threshold for voice activity detection. [-inf .. 60] dB (default: 3.5dB 20log10(1.5))"),
    ROS2Param(name="GAMMA_NN", value=1.100000, description="Over-subtraction factor of non- stationary noise. min .. max attenuation"),
    ROS2Param(name="GAMMA_NN_SR", value=1.100000, description="Over-subtraction factor of non-stationary noise for ASR.  [0.0 .. 3.0] (default: 1.1)"),
]
